"""add control functions module

Revision ID: 0f4fa19e22aa
Revises: 4dd9543aff89
Create Date: 2025-07-24 09:09:21.629192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0f4fa19e22aa'
down_revision: Union[str, Sequence[str], None] = '4dd9543aff89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('controlfunction',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('short_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('framework_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['framework_id'], ['controlframework.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_controlfunction_id'), 'controlfunction', ['id'], unique=False)
    
    # Use batch mode for SQLite compatibility
    with op.batch_alter_table('control', schema=None) as batch_op:
        batch_op.add_column(sa.Column('function_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.create_foreign_key('fk_control_function_id_controlfunction', 'controlfunction', ['function_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('control', schema=None) as batch_op:
        batch_op.drop_constraint('fk_control_function_id_controlfunction', type_='foreignkey')
        batch_op.drop_column('function_id')
    
    op.drop_index(op.f('ix_controlfunction_id'), table_name='controlfunction')
    op.drop_table('controlfunction')
    # ### end Alembic commands ###
