"""add_locked_field_to_asset_classes

Revision ID: 17cf77b6148a
Revises: 2d49d7a2a06f
Create Date: 2025-07-25 11:00:39.085112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '17cf77b6148a'
down_revision: Union[str, Sequence[str], None] = '2d49d7a2a06f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('controlassetclass', sa.Column('locked', sa.Boolean(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('controlassetclass', 'locked')
    # ### end Alembic commands ###
