"""add asset class relationships table

Revision ID: 2d49d7a2a06f
Revises: d4096b17c001
Create Date: 2025-07-24 15:48:07.164323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2d49d7a2a06f'
down_revision: Union[str, Sequence[str], None] = 'd4096b17c001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assetclassrelationship',
    sa.Column('parent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('child_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['controlassetclass.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['controlassetclass.id'], ),
    sa.PrimaryKeyConstraint('parent_id', 'child_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assetclassrelationship')
    # ### end Alembic commands ###
