"""add_short_name_to_controls_modules

Revision ID: 39db653f3d8c
Revises: 9f8f27ed610b
Create Date: 2025-07-23 11:13:05.645574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '39db653f3d8c'
down_revision: Union[str, Sequence[str], None] = '9f8f27ed610b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('control', sa.Column('short_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('controlframework', sa.Column('short_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('controlimplementationgroup', sa.Column('short_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('controlsafeguard', sa.Column('short_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('controlsafeguard', 'short_name')
    op.drop_column('controlimplementationgroup', 'short_name')
    op.drop_column('controlframework', 'short_name')
    op.drop_column('control', 'short_name')
    # ### end Alembic commands ###
