"""remove_implementation_group_id_from_controls

Revision ID: 3cf2a5b0df9e
Revises: 3d6aac1f68ed
Create Date: 2025-07-24 10:47:33.946011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3cf2a5b0df9e'
down_revision: Union[str, Sequence[str], None] = '3d6aac1f68ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('control', schema=None) as batch_op:
        batch_op.drop_column('implementation_group_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('control', schema=None) as batch_op:
        batch_op.add_column(sa.Column('implementation_group_id', sa.VARCHAR(), nullable=True))
        batch_op.create_foreign_key('fk_control_implementation_group', 'controlimplementationgroup', ['implementation_group_id'], ['id'])
    # ### end Alembic commands ###
