"""add_framework_id_to_safeguards

Revision ID: 3d6aac1f68ed
Revises: f8e3e135cbdb
Create Date: 2025-07-24 10:32:04.688341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3d6aac1f68ed'
down_revision: Union[str, Sequence[str], None] = 'f8e3e135cbdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('controlsafeguard', schema=None) as batch_op:
        batch_op.add_column(sa.Column('framework_id', sa.String(), nullable=True))
        batch_op.create_foreign_key('fk_controlsafeguard_framework', 'controlframework', ['framework_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('controlsafeguard', schema=None) as batch_op:
        batch_op.drop_constraint('fk_controlsafeguard_framework', type_='foreignkey')
        batch_op.drop_column('framework_id')
    # ### end Alembic commands ###
