"""Add framework_id foreign key to implementation groups

Revision ID: 4dd9543aff89
Revises: 39db653f3d8c
Create Date: 2025-07-23 15:01:04.169136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4dd9543aff89'
down_revision: Union[str, Sequence[str], None] = '39db653f3d8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('controlimplementationgroup', schema=None) as batch_op:
        batch_op.add_column(sa.Column('framework_id', sa.String(), nullable=True))
        batch_op.create_foreign_key('fk_controlimplementationgroup_framework_id', 'controlframework', ['framework_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('controlimplementationgroup', schema=None) as batch_op:
        batch_op.drop_constraint('fk_controlimplementationgroup_framework_id', type_='foreignkey')
        batch_op.drop_column('framework_id')
    # ### end Alembic commands ###
