"""add_framework_fk_to_functions_and_asset_classes

Revision ID: 67e7f418afb6
Revises: e2bb1061d927
Create Date: 2025-07-25 13:27:10.591004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '67e7f418afb6'
down_revision: Union[str, Sequence[str], None] = 'e2bb1061d927'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the existing framework_id column from controlassetclass (from failed constraint attempt)
    op.drop_column('controlassetclass', 'framework_id')
    
    # Add framework_id columns to both tables
    # SQLite doesn't support ALTER TABLE for foreign keys
    # Foreign key enforcement will be handled at the application level
    op.add_column('controlassetclass', sa.Column('framework_id', sa.String(), nullable=True))
    op.add_column('controlfunction', sa.Column('framework_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('controlfunction', 'framework_id')
    op.drop_column('controlassetclass', 'framework_id')
    # ### end Alembic commands ###
