"""add_safeguard_relationship_table

Revision ID: 6ec16068436f
Revises: 78cb3a852868
Create Date: 2025-07-25 14:04:45.504257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6ec16068436f'
down_revision: Union[str, Sequence[str], None] = '78cb3a852868'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('safeguardrelationship',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source_safeguard_id', sa.String(), nullable=False),
    sa.Column('target_safeguard_id', sa.String(), nullable=False),
    sa.Column('relationship_type', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['source_safeguard_id'], ['controlsafeguard.id'], ),
    sa.ForeignKeyConstraint(['target_safeguard_id'], ['controlsafeguard.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_safeguardrelationship_relationship_type'), 'safeguardrelationship', ['relationship_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: SQLite doesn't support dropping foreign key constraints directly
    # so we skip that operation
    op.drop_index(op.f('ix_safeguardrelationship_relationship_type'), table_name='safeguardrelationship')
    op.drop_table('safeguardrelationship')
    # ### end Alembic commands ###
