"""remove_framework_from_functions_v2

Revision ID: 7d73d672ca96
Revises: d3401c3ceb20
Create Date: 2025-07-24 09:40:55.764947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7d73d672ca96'
down_revision: Union[str, Sequence[str], None] = 'd3401c3ceb20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('controlfunction', schema=None) as batch_op:
        batch_op.drop_column('framework_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('controlfunction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('framework_id', sa.VARCHAR(), nullable=True))
        batch_op.create_foreign_key(None, 'controlframework', ['framework_id'], ['id'])
    # ### end Alembic commands ###
