"""Add Controls module

Revision ID: 9f8f27ed610b
Revises: 79febbeb42aa
Create Date: 2025-07-17 10:57:54.674773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9f8f27ed610b'
down_revision: Union[str, Sequence[str], None] = '79febbeb42aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('controlframework',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_controlframework_id'), 'controlframework', ['id'], unique=False)
    op.create_table('controlimplementationgroup',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_controlimplementationgroup_id'), 'controlimplementationgroup', ['id'], unique=False)
    op.create_table('control',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('framework_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('implementation_group_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['framework_id'], ['controlframework.id'], ),
    sa.ForeignKeyConstraint(['implementation_group_id'], ['controlimplementationgroup.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_control_id'), 'control', ['id'], unique=False)
    op.create_table('controlsafeguard',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('control_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['control_id'], ['control.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_controlsafeguard_id'), 'controlsafeguard', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_controlsafeguard_id'), table_name='controlsafeguard')
    op.drop_table('controlsafeguard')
    op.drop_index(op.f('ix_control_id'), table_name='control')
    op.drop_table('control')
    op.drop_index(op.f('ix_controlimplementationgroup_id'), table_name='controlimplementationgroup')
    op.drop_table('controlimplementationgroup')
    op.drop_index(op.f('ix_controlframework_id'), table_name='controlframework')
    op.drop_table('controlframework')
    # ### end Alembic commands ###
