"""add color fields to controls models

Revision ID: ac0048a0dae9
Revises: ecaad1e787cc
Create Date: 2025-07-24 13:04:16.486046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ac0048a0dae9'
down_revision: Union[str, Sequence[str], None] = 'ecaad1e787cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('control', sa.Column('color', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('controlframework', sa.Column('color', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('controlfunction', sa.Column('color', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('controlimplementationgroup', sa.Column('color', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('controlimplementationgroup', 'color')
    op.drop_column('controlfunction', 'color')
    op.drop_column('controlframework', 'color')
    op.drop_column('control', 'color')
    # ### end Alembic commands ###
