"""add asset classes table

Revision ID: d4096b17c001
Revises: ac0048a0dae9
Create Date: 2025-07-24 14:01:08.965057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd4096b17c001'
down_revision: Union[str, Sequence[str], None] = 'ac0048a0dae9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('controlassetclass',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('short_name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_controlassetclass_id'), 'controlassetclass', ['id'], unique=False)
    op.create_index(op.f('ix_controlassetclass_name'), 'controlassetclass', ['name'], unique=False)
    op.create_index(op.f('ix_controlassetclass_short_name'), 'controlassetclass', ['short_name'], unique=False)
    
    # Use batch mode for SQLite compatibility
    with op.batch_alter_table('control', schema=None) as batch_op:
        batch_op.add_column(sa.Column('asset_class_id', sa.String(), nullable=True))
        batch_op.create_foreign_key('fk_control_asset_class', 'controlassetclass', ['asset_class_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('control', schema=None) as batch_op:
        batch_op.drop_constraint('fk_control_asset_class', type_='foreignkey')
        batch_op.drop_column('asset_class_id')
    
    op.drop_index(op.f('ix_controlassetclass_short_name'), table_name='controlassetclass')
    op.drop_index(op.f('ix_controlassetclass_name'), table_name='controlassetclass')
    op.drop_index(op.f('ix_controlassetclass_id'), table_name='controlassetclass')
    op.drop_table('controlassetclass')
    # ### end Alembic commands ###
