"""add_asset_class_fk_to_safeguards

Revision ID: e2bb1061d927
Revises: 17cf77b6148a
Create Date: 2025-07-25 12:19:32.892357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e2bb1061d927'
down_revision: Union[str, Sequence[str], None] = '17cf77b6148a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('controlsafeguard', sa.Column('asset_class_id', sa.String(), nullable=True))
    # Note: Foreign key constraint will be enforced by SQLModel at the application level
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('controlsafeguard', 'asset_class_id')
    # ### end Alembic commands ###
