"""replace_framework_id_with_implementation_group_id_in_safeguards

Revision ID: ecaad1e787cc
Revises: 3cf2a5b0df9e
Create Date: 2025-07-24 11:02:03.590135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ecaad1e787cc'
down_revision: Union[str, Sequence[str], None] = '3cf2a5b0df9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('controlsafeguard', schema=None) as batch_op:
        batch_op.add_column(sa.Column('implementation_group_id', sa.VARCHAR(), nullable=True))
        batch_op.create_foreign_key('fk_controlsafeguard_implementation_group', 'controlimplementationgroup', ['implementation_group_id'], ['id'])
        batch_op.drop_column('framework_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('controlsafeguard', schema=None) as batch_op:
        batch_op.add_column(sa.Column('framework_id', sa.VARCHAR(), nullable=True))
        batch_op.create_foreign_key('fk_controlsafeguard_framework', 'controlframework', ['framework_id'], ['id'])
        batch_op.drop_column('implementation_group_id')
    # ### end Alembic commands ###
