"""remove_type_category_level_from_safeguards

Revision ID: f8e3e135cbdb
Revises: ff8531ba2e9b
Create Date: 2025-07-24 10:17:30.293033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f8e3e135cbdb'
down_revision: Union[str, Sequence[str], None] = 'ff8531ba2e9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('controlsafeguard', schema=None) as batch_op:
        batch_op.drop_column('category')
        batch_op.drop_column('level')
        batch_op.drop_column('type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('controlsafeguard', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('level', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('category', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
