"""update_safeguards_add_function_id_and_fields

Revision ID: ff8531ba2e9b
Revises: 7d73d672ca96
Create Date: 2025-07-24 10:07:34.932701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ff8531ba2e9b'
down_revision: Union[str, Sequence[str], None] = '7d73d672ca96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('controlsafeguard', schema=None) as batch_op:
        batch_op.add_column(sa.Column('function_id', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('type', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('category', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('level', sa.VARCHAR(), nullable=True))
        batch_op.alter_column('control_id', existing_type=sa.VARCHAR(), nullable=True)
        batch_op.create_foreign_key('fk_controlsafeguard_function_id', 'controlfunction', ['function_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('controlsafeguard', schema=None) as batch_op:
        batch_op.drop_constraint('fk_controlsafeguard_function_id', type_='foreignkey')
        batch_op.alter_column('control_id', existing_type=sa.VARCHAR(), nullable=False)
        batch_op.drop_column('level')
        batch_op.drop_column('category')
        batch_op.drop_column('type')
        batch_op.drop_column('function_id')
    # ### end Alembic commands ###
